- name: configure cart component
  hosts: cart
  become: yes
  tasks:
  - name: Disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: Install node js
    ansible.builtin.dnf:
      name: node js
      status: present

  - name: Craete systemUser
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes  #remote_src: yes means files already exist in cart server

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: Copy cart services to system
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes
      
