- name: configure frontend component
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      