- name: configure mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.command: dnf install mysql-server -y

  - name: start and enavble mysql
    ansible.buil.service:
      name: mysql
      state: started
      enabled: yes
  
  - name: Change default root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1