- name: configure payment module
  hosts: payment
  become: yes
  tasks:
  - name: install python3 package
    ansible.builtin.dnf:
      name:  "{{ item }}"
      state: installed
    loop:
    - python3
    - gcc
    - python3-devel

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: Download Application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: Unzip Application code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true


  - name: enable and start payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes