- name: user componentconfiguration
  hosts: user
  become: yes
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzip code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.npm:
      path: /app

  - name: copy user services
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes